"""Compatibility wrapper for usage metering helpers."""

from __future__ import annotations

from reopsai.shared.usage_metering import (
    BASE_WEIGHT_PRICE_PER_1M_USD,
    FEATURE_PREFIXES,
    INITIAL_COMPANY_WEIGHTED_TOKEN_GRANT,
    _LLM_USAGE_CONTEXT,
    _find_price,
    _request_context,
    _request_id_from_flask_context,
    _resolve_company_id_for_user,
    _resolve_primary_team_id,
    _resolve_team_id_for_user,
    _to_decimal,
    _to_int,
    _to_optional_int,
    build_llm_usage_context,
    calculate_cost_and_weighted_tokens,
    classify_feature_key,
    cleanup_old_llm_usage_events,
    ensure_company_initial_grant,
    extract_gemini_usage,
    extract_openai_usage,
    get_company_token_balance,
    get_llm_usage_context,
    is_company_quota_exceeded,
    record_company_usage_event,
    record_llm_call,
    record_team_usage_event,
    run_with_llm_usage_context,
    set_llm_usage_context,
    stream_with_llm_usage_context,
    track_llm_usage,
)

__all__ = [
    "BASE_WEIGHT_PRICE_PER_1M_USD",
    "FEATURE_PREFIXES",
    "INITIAL_COMPANY_WEIGHTED_TOKEN_GRANT",
    "_LLM_USAGE_CONTEXT",
    "_find_price",
    "_request_context",
    "_request_id_from_flask_context",
    "_resolve_company_id_for_user",
    "_resolve_primary_team_id",
    "_resolve_team_id_for_user",
    "_to_decimal",
    "_to_int",
    "_to_optional_int",
    "build_llm_usage_context",
    "calculate_cost_and_weighted_tokens",
    "classify_feature_key",
    "cleanup_old_llm_usage_events",
    "ensure_company_initial_grant",
    "extract_gemini_usage",
    "extract_openai_usage",
    "get_company_token_balance",
    "get_llm_usage_context",
    "is_company_quota_exceeded",
    "record_company_usage_event",
    "record_llm_call",
    "record_team_usage_event",
    "run_with_llm_usage_context",
    "set_llm_usage_context",
    "stream_with_llm_usage_context",
    "track_llm_usage",
]
